version: '3.3'

services:
    pmh1:
      build:
        context: ./
        dockerfile: Dockerfile
      networks:
        - default
      # volumes:
      #   - ./app/static/docs:/app/static/docs
      expose:
        - "80"   
      # ports: 
      #     - "80:80"                                                                                                         
      container_name: pmh1
      hostname: pmh1
      restart: always
    

networks:  
 default:
  external:
    name: ns2020-existing-network
    